before_script:
  - rm -rf ../plugin_tap
  - git clone https://gitlab.com/cpran/plugin_tap.git ../plugin_tap

Praat 5.4:
  script:
    - prove -v --exec "praat-5.4.00"
  tags:
    - cpran
  allow_failure: true

Praat 5.4.22:
  script:
    - prove -v --exec "praat-5.4.22 --ansi --pref-dir=../.."
  tags:
    - cpran
  allow_failure: true

Praat 6.0.03:
  script:
    - prove -v --exec "praat-6.0.03 --ansi --pref-dir=../.. --run"
  tags:
    - cpran
  allow_failure: true

Praat 6.0.13:
  script:
    - prove -v --exec "praat-6.0.13 --ansi --pref-dir=../.. --run"
  tags:
    - cpran
  allow_failure: true

Praat 6.0.14:
  script:
    - prove -v --exec "praat-6.0.14 --ansi --pref-dir=../.. --run"
  tags:
    - cpran
  allow_failure: true

Praat 6.0.15:
  script:
    - prove -v --exec "praat-6.0.15 --ansi --pref-dir=../.. --run"
  tags:
    - cpran
