image: jjatria/cpran:latest

variables:
  CPRAN_PREF_DIR: "/builds/$CI_PROJECT_NAMESPACE"

before_script:
  - cpran init
  - cpran update
  - cpran deps | cpran --yes install --notest -

Praat:
  script:
    - prove -v --exec "praat --ansi --pref-dir=$CPRAN_PREF_DIR --run"
  tags:
    - cpran
